# Generated by Django 3.2 on 2021-11-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_blockdays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockDays',
            new_name='BlockDay',
        ),
    ]
